application: <your_app_id>
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /scripts
  static_dir: static/scripts

- url: /img
  static_dir: static/img

- url: /fonts
  static_dir: static/fonts

- url: /.*
  script: main.py

libraries:
- name: django
  version: "1.2"

builtins:
- remote_api: on
